### ISSUE TITLE
Building fails on Windows with Mingw64

### ISSUE THREAD

**Issue by michikommader** [grepthat/libOpenDRIVE#81]
Since commit df54501, where signal support has been added, my build fails on Windows with g++ through Mingw64 with POSIX thread model. Some errors:

```
C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/locale_classes.h:559:18: error: '__atomic_add_dispatch' is not a member of '__gnu_cxx'
C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/locale_classes.h:388:12: error: '__gthread_once_t' does not name a type
C:/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/locale_classes.h:405:40: error: class 'std::locale::facet' does not have any field named '_M_refcount'
```

The same with GCC version 13.1.0. Does anybody have experience with such an environment? Maybe @pranavashok who provided the new features? 😊

**Comment by michikommader** [comment]
It builds with GCC 13.1.0 when using win32 instead of posix thread model.
